services:
  # Backend API Service
  - type: web
    name: cursorrulecraft-api
    runtime: docker
    region: singapore
    plan: free # Upgrade from hobby for better performance
    branch: main
    # Using Nx-generated Dockerfile (with @nx/docker plugin)
    dockerfilePath: ./apps/backend/Dockerfile
    dockerContext: .
    buildFilter:
      paths:
        - apps/backend/**
        - packages/shared-types/**
        - apps/backend/Dockerfile
        - package.json
        - bun.lock
        - nx.json
        - tsconfig.base.json
        - tsconfig.json
      ignoredPaths:
        - '**/*.md'
        - '**/README.md'
        - docs/**
        - '**/*.test.ts'
        - '**/*.spec.ts'
        - .github/**
        - '**/.gitignore'
        - '**/LICENSE'
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: HOST
        value: 0.0.0.0

      # Supabase Configuration
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false

      # Clerk Authentication
      - key: CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false

      # GitHub App Configuration
      - key: GITHUB_APP_ID
        sync: false
      - key: GITHUB_APP_PRIVATE_KEY_BASE64
        sync: false

      # GitHub OAuth (from GitHub App settings)
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false

      # URLs - Backend needs to know where frontend is
      - key: GITHUB_REDIRECT_URI
        value: https://cursorrulecraft.onrender.com/api/auth/github/callback
      - key: FRONTEND_URL
        value: https://cursorrulecraft.onrender.com

    # Health check on /api/health endpoint
    healthCheckPath: /api/health

    # Auto-deploy on push
    autoDeploy: true

  # Frontend Static Site (served via nginx in Docker)
  - type: web
    name: cursorrulecraft
    runtime: docker
    region: singapore
    plan: free
    branch: main
    # Using frontend Dockerfile (self-contained multi-stage build)
    dockerfilePath: ./apps/frontend/Dockerfile
    dockerContext: .
    # Pass build args for Vite
    dockerBuildArgs:
      - name: VITE_API_URL
        value: https://cursorrulecraft-api.onrender.com/api
      - name: VITE_CLERK_PUBLISHABLE_KEY
        sync: false
    envVars:
      - key: PORT
        value: 4000
    buildFilter:
      paths:
        - apps/frontend/**
        - apps/frontend/Dockerfile
        - apps/frontend/nginx.conf.template
        - package.json
        - bun.lock
        - nx.json
        - tsconfig.base.json
        - tsconfig.json
      ignoredPaths:
        - '**/*.md'
        - '**/README.md'
        - docs/**
        - '**/*.test.ts'
        - '**/*.spec.ts'
        - .github/**
        - '**/.gitignore'
        - '**/LICENSE'

    # Auto-deploy on push
    autoDeploy: true
