services:
  # Backend API Service
  - type: web
    name: cursorrulecraft-api
    runtime: docker
    region: singapore
    plan: hobby # Upgrade from hobby for better performance
    branch: main
    dockerfilePath: ./Dockerfile.backend
    dockerContext: .
    buildFilter:
      paths:
        - apps/backend/**
        - packages/shared-types/**
        - Dockerfile.backend
        - package.json
        - bun.lock
        - nx.json
        - tsconfig.base.json
        - tsconfig.json
      ignoredPaths:
        - '**/*.md'
        - '**/README.md'
        - docs/**
        - '**/*.test.ts'
        - '**/*.spec.ts'
        - .github/**
        - '**/.gitignore'
        - '**/LICENSE'
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: HOST
        value: 0.0.0.0

      # Supabase Configuration
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false

      # Clerk Authentication
      - key: CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: CLERK_WEBHOOK_SECRET
        sync: false

      # GitHub App Configuration
      - key: GITHUB_APP_ID
        sync: false
      - key: GITHUB_APP_PRIVATE_KEY_BASE64
        sync: false
      - key: GITHUB_APP_CLIENT_ID
        sync: false
      - key: GITHUB_APP_CLIENT_SECRET
        sync: false
      - key: GITHUB_APP_WEBHOOK_SECRET
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false

      # URLs - Backend needs to know where frontend is
      - key: GITHUB_REDIRECT_URI
        value: https://cursorrulecraft.onrender.com/api/auth/github/callback
      - key: FRONTEND_URL
        value: https://cursorrulecraft.onrender.com
      - key: ALLOWED_ORIGINS
        value: https://cursorrulecraft.onrender.com

    # Health check on /api/health endpoint
    healthCheckPath: /api/health

    # Auto-deploy on push
    autoDeploy: true

  # Frontend Static Site (served via nginx in Docker)
  - type: web
    name: cursorrulecraft
    runtime: docker
    region: singapore
    plan: hobby
    branch: main
    dockerfilePath: ./Dockerfile.frontend
    dockerContext: .
    buildFilter:
      paths:
        - apps/frontend/**
        - packages/shared-types/**
        - Dockerfile.frontend
        - package.json
        - bun.lock
        - nx.json
        - tsconfig.base.json
        - tsconfig.json
      ignoredPaths:
        - '**/*.md'
        - '**/README.md'
        - docs/**
        - '**/*.test.ts'
        - '**/*.spec.ts'
        - .github/**
        - '**/.gitignore'
        - '**/LICENSE'

    # Environment variables for build-time
    envVars:
      - key: VITE_CLERK_PUBLISHABLE_KEY
        sync: false
      # Frontend will make API requests to the backend service
      - key: VITE_API_URL
        value: https://cursorrulecraft-api.onrender.com/api

    # Build arguments
    dockerBuildArgs:
      - key: VITE_API_URL
        value: https://cursorrulecraft-api.onrender.com/api
      - key: VITE_CLERK_PUBLISHABLE_KEY
        fromEnvVar: VITE_CLERK_PUBLISHABLE_KEY

    # Auto-deploy on push
    autoDeploy: true
